#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const CACHE = path.join(ROOT, "work", "rivstart-vocabulary-enrichments.jsonl");
const ENRICHED_JSON = path.join(ROOT, "Rivstart Resources", "rivstart-vocabulary.enriched.json");
const ENRICHED_JS = path.join(ROOT, "Rivstart Resources", "rivstart-vocabulary.enriched.js");
const SVERIGE_JSON = path.join(ROOT, "Sverige Resources", "sverige-vocabulary.json");
const SVERIGE_JS = path.join(ROOT, "Sverige Resources", "sverige-vocabulary.js");
const BAD_PREFIX = /^\s*(中文释义|英文释义)\s*[:：]\s*/;

const stats = {
  cacheFixed: 0,
  enrichedFixed: 0,
  sverigeFixed: 0,
  translated: 0,
  fallback: 0,
};

function main() {
  fixCache();
  fixVocabularyJson(ENRICHED_JSON, ENRICHED_JS, "window.RIVSTART_VOCABULARY", "enrichedFixed");
  fixVocabularyJson(SVERIGE_JSON, SVERIGE_JS, "window.SVERIGE_VOCABULARY", "sverigeFixed");
  console.log(JSON.stringify(stats, null, 2));
}

function fixCache() {
  if (!fs.existsSync(CACHE)) return;
  const lines = fs.readFileSync(CACHE, "utf8").split(/\r?\n/).filter(Boolean);
  const out = lines.map((line) => {
    const item = JSON.parse(line);
    if (!shouldFixMeaning(item.meaning_zh, item.quality_note, item.meaning_en)) return JSON.stringify(item);
    const fixed = translateMeaning(String(item.meaning_zh || item.meaning_en || "").replace(BAD_PREFIX, ""), item.meaning_en || "");
    item.meaning_zh = fixed.text;
    item.quality_note = fixed.review
      ? mergeQualityNote(item.quality_note, "needs_zh_review")
      : removeQualityNote(item.quality_note, "needs_zh_review");
    stats.cacheFixed += 1;
    return JSON.stringify(item);
  });
  fs.writeFileSync(CACHE, `${out.join("\n")}\n`, "utf8");
}

function fixVocabularyJson(jsonFile, jsFile, globalName, statKey) {
  const payload = JSON.parse(fs.readFileSync(jsonFile, "utf8"));
  payload.entries = payload.entries.map((entry) => {
    if (!shouldFixMeaning(entry.meaning_zh, entry.enrichment_quality_note, entry.meaning_en)) return entry;
    const fixed = translateMeaning(String(entry.meaning_zh || entry.meaning_en || "").replace(BAD_PREFIX, ""), entry.meaning_en || "");
    stats[statKey] += 1;
    return {
      ...entry,
      meaning_zh: fixed.text,
      enrichment_quality_note: fixed.review
        ? mergeQualityNote(entry.enrichment_quality_note, "needs_zh_review")
        : removeQualityNote(entry.enrichment_quality_note, "needs_zh_review"),
    };
  });
  payload.enrichment = {
    ...(payload.enrichment || {}),
    meaning_zh_batch_fixed_at: new Date().toISOString(),
    meaning_zh_fallback_policy: "English fallback is kept only when no local Chinese mapping exists; marked with needs_zh_review.",
  };
  fs.writeFileSync(jsonFile, JSON.stringify(payload, null, 2), "utf8");
  const js = globalName === "window.SVERIGE_VOCABULARY"
    ? `${globalName} = ${JSON.stringify(payload)};\nwindow.RIVSTART_VOCABULARY = window.SVERIGE_VOCABULARY;\n`
    : `${globalName} = ${JSON.stringify(payload)};\n`;
  fs.writeFileSync(jsFile, js, "utf8");
}

function isBadMeaning(value) {
  return BAD_PREFIX.test(String(value || ""));
}

function shouldFixMeaning(value, note = "", meaningEn = "") {
  const text = String(value || "");
  if (isBadMeaning(text)) return true;
  if (!clean(text) && clean(meaningEn)) return true;
  if (clean(meaningEn) && !hasChinese(text)) return true;
  return String(note || "").includes("needs_zh_review") && !hasChinese(text);
}

function translateMeaning(rawMeaning, meaningEn = "") {
  const original = clean(rawMeaning || meaningEn);
  if (!original) return reviewed("待校对释义");
  const direct = lookup(original);
  if (direct) return translated(direct);

  const cleaned = stripDecorators(original);
  const cleanedDirect = lookup(cleaned);
  if (cleanedDirect) return translated(cleanedDirect);

  const split = splitMeaning(cleaned);
  if (split.length > 1) {
    const parts = split.map((part) => translateMeaning(part).text).filter(Boolean);
    const review = parts.some((part) => !hasChinese(part));
    return review ? reviewed(parts.join("；")) : translated(parts.join("；"));
  }

  const normalized = normalize(cleaned);
  const phrase = phraseTranslations[normalized];
  if (phrase) return translated(phrase);

  const words = normalized.split(/\s+/).filter(Boolean);
  if (words.length > 1) {
    const composition = translateComposedPhrase(words);
    if (composition) return translated(composition);
  }

  const single = wordTranslations[singularize(normalized)] || wordTranslations[normalized];
  if (single) return translated(single);

  return reviewed(original);
}

function splitMeaning(text) {
  return text
    .split(/\s*(?:;|,|\/|\bor\b)\s*/i)
    .map((part) => clean(part))
    .filter(Boolean);
}

function stripDecorators(text) {
  return clean(text)
    .replace(/^(?:a|an|the)\s+/i, "")
    .replace(/^to\s+/i, "")
    .replace(/^be\s+/i, "")
    .replace(/^someone who\s+/i, "person who ")
    .replace(/^something that\s+/i, "thing that ");
}

function translateComposedPhrase(words) {
  const joined = words.join(" ");
  if (phraseTranslations[joined]) return phraseTranslations[joined];
  if (words[0] === "person" && words[1] === "who") {
    const action = translateMeaning(words.slice(2).join(" ")).text;
    return hasChinese(action) ? `${action}的人` : "";
  }
  if (words[0] === "thing" && words[1] === "that") {
    const action = translateMeaning(words.slice(2).join(" ")).text;
    return hasChinese(action) ? `${action}的东西` : "";
  }
  const translatedWords = words.map((word) => wordTranslations[singularize(word)] || wordTranslations[word] || "");
  const known = translatedWords.filter(Boolean).length;
  if (!known || known < Math.ceil(words.length * 0.75)) return "";
  return translatedWords.filter(Boolean).join("");
}

function lookup(value) {
  return phraseTranslations[normalize(value)] || wordTranslations[normalize(value)] || wordTranslations[singularize(normalize(value))] || "";
}

function singularize(value) {
  if (wordTranslations[value]) return value;
  if (value.endsWith("ies")) return `${value.slice(0, -3)}y`;
  if (value.endsWith("es")) return value.slice(0, -2);
  if (value.endsWith("s") && value.length > 3) return value.slice(0, -1);
  return value;
}

function translated(text) {
  stats.translated += 1;
  return { text, review: false };
}

function reviewed(text) {
  stats.fallback += 1;
  return { text, review: true };
}

function mergeQualityNote(existing, note) {
  const parts = clean(existing).split(/\s*;\s*/).filter(Boolean);
  if (note && !parts.includes(note)) parts.push(note);
  return parts.join("; ");
}

function removeQualityNote(existing, note) {
  return clean(existing)
    .split(/\s*;\s*/)
    .filter((part) => part && part !== note)
    .join("; ");
}

function clean(value) {
  return String(value || "").replace(/\s+/g, " ").trim();
}

function normalize(value) {
  return clean(value).toLowerCase().replace(/[“”"]/g, "").replace(/[.!?？！。]+$/g, "");
}

function hasChinese(value) {
  return /[\u4e00-\u9fff]/.test(value);
}

const phraseTranslations = {
  "a little": "一点；少量",
  "a lot": "很多",
  "a lot of": "许多",
  "a tiny bit": "一点点",
  "absolutely not": "绝对不是；绝对不行",
  "all/everyone": "全部；每个人",
  "around the clock": "全天候；昼夜不停",
  "as well": "也；同样",
  "at least": "至少",
  "baltic sea": "波罗的海",
  "biodiversity": "生物多样性",
  "book a room/place to live": "预订房间或住处",
  "be able to": "能够",
  "be called": "叫作；名叫",
  "be located": "位于",
  "be run out of": "被赶出；被逐出",
  "be taken seriously": "被认真对待",
  "best friend": "最好的朋友",
  "cell phone": "手机",
  "christmas food": "圣诞食物",
  "ciao see you": "再见；回头见",
  "ciao! see you": "再见；回头见",
  "compound words": "复合词",
  "completely dead": "完全死了；毫无生气",
  "completely sick/crazy": "完全病态；非常疯狂",
  "computer knowledge": "计算机知识",
  "concerned with status": "看重地位；有身份意识",
  "concert hall": "音乐厅",
  "constitutional monarchy": "君主立宪制",
  "contact with the ground": "与地面接触",
  "could you say that again": "你能再说一遍吗",
  "could you say that again?": "你能再说一遍吗",
  "do you follow": "你明白了吗",
  "do you follow?": "你明白了吗",
  "coffee break": "咖啡休息；茶歇",
  "compound": "复合的；复合词",
  "containing social criticism": "带有社会批判性的",
  "correct answer": "正确答案",
  "come from": "来自",
  "do make": "做；制作",
  "do, make": "做；制作",
  "denmark": "丹麦",
  "don't make a big deal out of it": "别把这件事看得太严重",
  "easter holiday": "复活节假期",
  "each other": "彼此",
  "excuse me i'm sorry do you have a moment": "不好意思，你有时间吗",
  "excuse me/i'm sorry do you have a moment": "不好意思，你有时间吗",
  "female teacher": "女教师",
  "fall in love": "相爱；坠入爱河",
  "find out": "查明；弄清",
  "for fun": "为了好玩",
  "from where": "从哪里",
  "get married": "结婚",
  "give up": "放弃",
  "go away": "离开",
  "grow up": "长大",
  "greenlandic": "格陵兰语；格陵兰的",
  "hardworking": "勤奋的",
  "harmonious": "和谐的",
  "happiness surge": "幸福感激增",
  "have to": "必须；不得不",
  "hi it's been a long time": "嗨，好久不见",
  "hi! it's been a long time!": "嗨，好久不见",
  "hope you are all well": "希望你们一切都好",
  "hope you are all well!": "希望你们一切都好",
  "how many": "多少",
  "how many?": "多少",
  "i don't understand": "我不明白",
  "i found on the internet": "我在网上找到了",
  "i found… on the internet": "我在网上找到了",
  "i'm fine": "我很好",
  "i see": "我明白了；原来如此",
  "in conjunction with": "与……结合；连同",
  "in the end": "最后；最终",
  "in the end…": "最后；最终",
  "in fact": "事实上",
  "in front of": "在……前面",
  "instead of": "代替；而不是",
  "instead of…": "代替；而不是",
  "information technology": "信息技术",
  "interested in": "对……感兴趣",
  "it company": "信息技术公司；IT 公司",
  "17th century": "17 世纪",
  "lie be situated": "位于；坐落",
  "lie, be situated": "位于；坐落",
  "look after": "照顾",
  "look for": "寻找",
  "mixed candy": "混合糖果",
  "mitigating circumstances": "减轻情节",
  "make way for": "为……让路",
  "mobile phone": "手机",
  "more or less": "差不多；或多或少",
  "national park": "国家公园",
  "my name is": "我的名字是",
  "never ever": "绝不；从不",
  "next to": "在……旁边",
  "opera singer": "歌剧歌手",
  "one punch": "一拳",
  "på": "遇到；碰到",
  "no i see": "不是；我明白了",
  "no ; i see": "不是；我明白了",
  "non": "非；不",
  "not at all": "一点也不；不用谢",
  "now and then": "时不时；偶尔",
  "of course": "当然",
  "on the sly": "偷偷地",
  "percent": "百分比；百分之",
  "policeman/woman": "警察",
  "paint someone who": "描绘某人",
  "prime minister": "首相；总理",
  "push boundaries": "突破界限",
  "question words": "疑问词",
  "rather than": "而不是",
  "relate to": "涉及；与……有关",
  "result in": "导致",
  "secondhand smoke": "二手烟",
  "self disclosure": "自我披露",
  "sharpen your ears": "竖起耳朵听；仔细听",
  "solid genuine": "可靠的；真诚的",
  "solid, genuine": "可靠的；真诚的",
  "stand close": "站得近；关系亲近",
  "subject pronoun": "主语代词",
  "take over": "接管",
  "take place": "发生；举行",
  "talk about": "谈论",
  "time period": "时期；时间段",
  "to be arrested": "被逮捕",
  "to meet": "见面；遇见",
  "to sign": "签名；签署",
  "watch out for": "小心；注意",
  "well known": "知名的；著名的",
};

const wordTranslations = {
  "a/an": "一个；一",
  "about": "关于；大约",
  "abstain": "戒除；弃权",
  "accept": "接受",
  "accountant": "会计",
  "achieve": "实现；达成",
  "actually": "实际上",
  "admonition": "告诫；警告",
  "advance": "预付款；进展",
  "advocate": "倡导；主张",
  "after": "在……之后",
  "again": "再次",
  "age": "年龄；年代",
  "agree": "同意",
  "aim": "瞄准；旨在",
  "all": "全部；所有",
  "amongst": "在……之中",
  "and": "和；与",
  "answer": "回答；答案",
  "appear": "出现；显得",
  "ask": "问；请求",
  "associate": "联想；联系",
  "at": "在；于",
  "attract": "吸引",
  "avoid": "避免",
  "babble": "咿呀学语；胡言乱语",
  "back": "回来；背部；后面",
  "bad": "坏的；不好的",
  "bank": "银行",
  "be": "是；成为",
  "before": "在……之前",
  "behave": "表现；行为",
  "belong": "属于",
  "below": "在下面",
  "best": "最好的",
  "beyond": "超出；在……之外",
  "big": "大的",
  "board": "板；委员会",
  "book": "书",
  "both": "两者都",
  "box": "盒子；方框",
  "boy": "男孩",
  "boyfriend": "男朋友",
  "breathless": "喘不过气的",
  "brief": "简短的；短暂的",
  "broken": "破碎的；坏掉的",
  "bus": "公共汽车",
  "calculate": "计算",
  "call": "打电话；称呼",
  "can": "会；能够",
  "cause": "导致；原因",
  "change": "改变；变化",
  "chapter": "章节",
  "characteristic": "特征；特点",
  "chef": "厨师",
  "child": "孩子",
  "children": "孩子们",
  "city": "城市",
  "claim": "声称；要求",
  "class": "班级；课",
  "clear": "清楚的；明确的",
  "climb": "攀登；爬",
  "coffee": "咖啡",
  "cold": "冷的",
  "colombia": "哥伦比亚",
  "come": "来",
  "common": "常见的；共同的",
  "company": "公司",
  "complete": "完整的；完成",
  "completely": "完全地",
  "complicated": "复杂的",
  "conscience": "良心",
  "consonant": "辅音",
  "continuously": "连续地；不断地",
  "contradict": "反驳；矛盾",
  "cool": "酷的；凉爽的",
  "course": "课程",
  "crack": "裂缝；破裂",
  "craving": "渴望",
  "current": "当前的；电流",
  "deaf": "聋的",
  "dentist": "牙医",
  "design": "设计",
  "designer": "设计师",
  "determine": "决定；确定",
  "develop": "发展；开发",
  "dialogue": "对话",
  "die": "死亡",
  "difficult": "困难的",
  "discovery": "发现",
  "division": "分裂；部门",
  "divorce": "离婚",
  "divorced": "离婚的",
  "doctor": "医生",
  "down": "向下",
  "drink": "喝；饮料",
  "driver": "司机",
  "drown": "溺水；淹没",
  "easy": "容易的",
  "eat": "吃",
  "edged": "被挤开；带边的",
  "emphasis": "强调",
  "end": "结束；末尾",
  "engineer": "工程师",
  "english": "英语；英国的",
  "enough": "足够",
  "ever": "曾经；永远",
  "every": "每个",
  "example": "例子",
  "exile": "流亡者；流放",
  "executioner": "刽子手",
  "exercise": "练习；锻炼",
  "expect": "期待；预期",
  "expected": "预期的",
  "experience": "经历；经验",
  "father": "父亲",
  "feel": "感觉",
  "fight": "战斗；斗争",
  "fighting": "战斗的",
  "financially": "在财务上",
  "find": "找到",
  "flashlight": "手电筒",
  "flower": "花",
  "focus": "集中；焦点",
  "for": "为了；给",
  "force": "力量；迫使",
  "free": "自由的；免费的",
  "french": "法语；法国的",
  "friend": "朋友",
  "fun": "有趣；乐趣",
  "future": "未来",
  "gap": "差距；缺口",
  "general": "一般的；将军",
  "german": "德语；德国的",
  "girlfriend": "女朋友",
  "go": "去",
  "good": "好的",
  "gracious": "亲切的；仁慈的",
  "great": "伟大的；很大的",
  "group": "小组",
  "grow": "成长",
  "grumpy": "脾气坏的",
  "hairdresser": "理发师",
  "hardly": "几乎不",
  "have": "有",
  "he": "他",
  "heal": "治愈",
  "healthy": "健康的",
  "hear": "听见",
  "here": "这里",
  "hi": "你好",
  "hi!": "你好！",
  "highlight": "亮点；强调",
  "hold": "握住；持有",
  "hot": "热的",
  "however": "然而",
  "hurt": "受伤；伤害",
  "i": "我",
  "illness": "疾病",
  "imagine": "想象",
  "implement": "实施；工具",
  "impolite": "不礼貌的",
  "improve": "改善；提高",
  "in": "在……里；在",
  "incubator": "孵化器",
  "independent": "独立的",
  "indescribable": "难以形容的",
  "infection": "感染",
  "information": "信息",
  "inherit": "继承",
  "introduce": "介绍",
  "inventive": "有创造力的",
  "ireland": "爱尔兰",
  "italian": "意大利语；意大利的",
  "italy": "意大利",
  "it": "它；这",
  "job": "工作；职业",
  "judge": "法官；判断",
  "keen": "热衷的；敏锐的",
  "know": "知道；会",
  "language": "语言",
  "lavish": "奢华的；慷慨的",
  "lawyer": "律师",
  "lean": "倾斜；瘦的",
  "lie": "躺；位于；说谎",
  "light": "光；轻的",
  "limitless": "无限的",
  "line": "线；行",
  "listen": "听",
  "lively": "活泼的",
  "long": "长的",
  "look": "看；寻找",
  "mansion": "豪宅",
  "mark": "标记；分数",
  "marriage": "婚姻",
  "mean": "意思是；意味着",
  "measure": "测量；措施",
  "meadow": "草地",
  "meet": "见面；遇见",
  "member": "成员",
  "mention": "提到",
  "merciless": "无情的",
  "mess": "混乱；一团糟",
  "mingle": "交往；混合",
  "mischievous": "淘气的",
  "mostly": "主要地；大多",
  "move": "移动；搬家",
  "my": "我的",
  "namely": "即；也就是",
  "naughty": "淘气的",
  "negation": "否定",
  "never": "从不",
  "new": "新的",
  "next": "下一个",
  "no": "不；没有",
  "northern": "北部的",
  "now": "现在",
  "nowadays": "如今",
  "number": "数字；号码",
  "nurse": "护士",
  "obvious": "明显的",
  "occur": "发生；出现",
  "of": "……的",
  "old": "旧的；老的",
  "on": "在……上",
  "one": "一；一个",
  "only": "只；仅仅",
  "open": "打开；开放的",
  "opponent": "对手",
  "oppressor": "压迫者",
  "or": "或者；还是",
  "other": "其他的",
  "outside": "外面；在外面",
  "own": "自己的；拥有",
  "page": "页；页面",
  "paper": "纸；纸张",
  "parliament": "议会",
  "peace": "和平",
  "performance": "表现；演出",
  "periodically": "周期性地",
  "person": "人",
  "philosophy": "哲学",
  "photographer": "摄影师",
  "place": "地方；放置",
  "plant": "植物；种植",
  "play": "玩；演奏",
  "pleasant": "愉快的；宜人的",
  "pleased": "高兴的；满意的",
  "point": "点；指出",
  "position": "位置",
  "power": "力量；权力",
  "powerful": "强大的",
  "practice": "练习",
  "preschool": "幼儿园",
  "prime": "主要的；首要的",
  "probably": "可能；大概",
  "produce": "生产；产生",
  "profession": "职业",
  "pronoun": "代词",
  "pronounce": "发音",
  "psychology": "心理学",
  "publisher": "出版商",
  "pursue": "追求；从事",
  "question": "问题",
  "quit": "退出；放弃",
  "rather": "相当；宁愿",
  "reach": "到达；达到",
  "read": "读；阅读",
  "reason": "原因；理由",
  "recovery": "恢复",
  "reflect": "反映；思考",
  "remain": "保持；留下",
  "replace": "替换；取代",
  "repetition": "重复",
  "restaurant": "餐厅",
  "retiree": "退休者",
  "return": "返回；归还",
  "reversed": "反向的；颠倒的",
  "say": "说",
  "scattered": "分散的",
  "second": "第二；秒",
  "semblance": "表象；外观",
  "sense": "感觉；意义",
  "sentence": "句子",
  "separate": "分开的；分离",
  "serve": "服务；提供",
  "she": "她",
  "shine": "发光",
  "short": "短的；矮的",
  "shoulder": "肩膀",
  "show": "显示；展示",
  "signature": "签名",
  "similar": "相似的",
  "since": "自从；因为",
  "single": "单个的；单身的",
  "situation": "情况；情形",
  "slip": "纸条；滑倒",
  "small": "小的",
  "so": "所以；如此",
  "some": "一些",
  "sound": "声音；听起来",
  "sovereign": "主权的；君主",
  "spanish": "西班牙语；西班牙的",
  "special": "特别的",
  "spread": "传播；展开",
  "sprawled": "摊开的；伸展的",
  "stand": "站立",
  "step": "步骤；迈步",
  "strange": "奇怪的",
  "strive": "努力；奋斗",
  "study": "学习；研究",
  "substantial": "大量的；实质性的",
  "suffer": "遭受",
  "suitable": "合适的",
  "surprising": "令人惊讶的",
  "swedish": "瑞典语；瑞典的",
  "swiss": "瑞士的；瑞士人",
  "system": "系统",
  "talented": "有天赋的",
  "talk": "说话；谈论",
  "template": "模板",
  "then": "然后；那时",
  "they": "他们；她们；它们",
  "three": "三",
  "time": "时间",
  "to": "到；向；给",
  "tough": "艰难的；强硬的",
  "tray": "托盘",
  "travel": "旅行",
  "trial": "审判；试验",
  "try": "尝试",
  "turn": "转动；轮到",
  "two": "二",
  "ukraine": "乌克兰",
  "unfaithful": "不忠的",
  "unhealthy": "不健康的",
  "university": "大学",
  "unmoved": "无动于衷的",
  "unrestricted": "不受限制的",
  "up": "向上",
  "vain": "徒劳的；自负的",
  "verb": "动词",
  "visit": "参观；拜访",
  "vokal": "元音",
  "vowel": "元音",
  "waiter": "服务员",
  "warm": "温暖的",
  "water": "水",
  "wave": "波浪；挥手",
  "web": "网页；网络",
  "weed": "杂草",
  "well": "好；井",
  "what": "什么",
  "where": "哪里",
  "which": "哪一个",
  "whimsical": "异想天开的",
  "wife": "妻子",
  "with": "和；带有",
  "without": "没有；不带",
  "witty": "机智的",
  "woo": "追求；求爱",
  "word": "词；单词",
  "work": "工作",
  "writer": "作家",
  "write": "写",
  "yes": "是；对",
  "youngest": "最年轻的",
  "your": "你的；你们的",
};

Object.assign(phraseTranslations, {
  "and you": "那你呢？",
  "circle": "圈出；画圈",
  "good luck": "祝你好运",
  "great!": "太好了！",
  "great!/how fun!": "太好了！真有趣！",
  "make an x": "打叉；画叉",
  "my name is": "我的名字是",
  "speak swedish": "说瑞典语",
  "that’s great": "那太好了",
  "that is great": "那太好了",
  "tick": "打勾；勾选",
  "what is your name?": "你叫什么名字？",
  "what languages do you speak?": "你会说哪些语言？",
  "you speak swedish!": "你会说瑞典语！",
  "be in touch": "保持联系",
  "football soccer player": "足球运动员",
  "good-looking": "好看的；漂亮的",
  "ice hockey": "冰球",
  "in love": "恋爱中；相爱的",
  "point out": "指出",
  "special offer": "特价优惠",
  "strawberry cake": "草莓蛋糕",
});

Object.assign(wordTranslations, {
  "account": "账户；账目",
  "accounts": "账目；会计",
  "advertisement": "广告",
  "airport": "机场",
  "almost": "几乎",
  "alone": "独自；单独",
  "already": "已经",
  "also": "也",
  "always": "总是",
  "angry": "生气的",
  "animal": "动物",
  "apartment": "公寓",
  "apple": "苹果",
  "appointment": "预约；约会",
  "area": "区域；面积",
  "arm": "手臂",
  "arrive": "到达",
  "article": "文章；物品",
  "autumn": "秋天",
  "baby": "婴儿",
  "bag": "包",
  "ball": "球",
  "bathroom": "浴室；卫生间",
  "beautiful": "美丽的",
  "because": "因为",
  "become": "成为；变得",
  "bed": "床",
  "beer": "啤酒",
  "begin": "开始",
  "behind": "在……后面",
  "believe": "相信",
  "bicycle": "自行车",
  "bill": "账单",
  "bird": "鸟",
  "birthday": "生日",
  "black": "黑色的",
  "blue": "蓝色的",
  "boat": "船",
  "body": "身体",
  "bread": "面包",
  "break": "打破；休息",
  "breakfast": "早餐",
  "bring": "带来",
  "brother": "兄弟",
  "brown": "棕色的",
  "build": "建造",
  "building": "建筑物",
  "business": "商业；事务",
  "busy": "忙碌的",
  "buy": "买",
  "cake": "蛋糕",
  "car": "汽车",
  "card": "卡片",
  "care": "照顾；关心",
  "careful": "小心的",
  "carry": "携带",
  "cat": "猫",
  "century": "世纪",
  "chair": "椅子",
  "cheap": "便宜的",
  "cheese": "奶酪",
  "cinema": "电影院",
  "clean": "清洁的；打扫",
  "clock": "钟；时钟",
  "close": "关闭；近的",
  "clothes": "衣服",
  "cloud": "云",
  "club": "俱乐部",
  "coat": "外套",
  "color": "颜色",
  "colour": "颜色",
  "computer": "电脑",
  "concert": "音乐会",
  "continue": "继续",
  "cook": "做饭；厨师",
  "copy": "复制；副本",
  "corner": "角落",
  "cost": "花费；费用",
  "countryside": "乡村",
  "create": "创造",
  "culture": "文化",
  "cup": "杯子",
  "dance": "跳舞",
  "dangerous": "危险的",
  "daughter": "女儿",
  "day": "天；日",
  "dear": "亲爱的；昂贵的",
  "decide": "决定",
  "deep": "深的",
  "describe": "描述",
  "desk": "书桌",
  "different": "不同的",
  "dinner": "晚餐",
  "dirty": "脏的",
  "dish": "盘子；菜肴",
  "dog": "狗",
  "door": "门",
  "dream": "梦；梦想",
  "dress": "连衣裙；穿衣",
  "early": "早的",
  "earth": "地球；土地",
  "economics": "经济学",
  "education": "教育",
  "egg": "鸡蛋",
  "eight": "八",
  "eighteen": "十八",
  "eighty": "八十",
  "eleven": "十一",
  "email": "电子邮件",
  "empty": "空的",
  "even": "甚至；平坦的",
  "evening": "晚上",
  "everyone": "每个人",
  "everything": "一切",
  "expensive": "昂贵的",
  "explain": "解释",
  "eye": "眼睛",
  "family": "家庭；家人",
  "famous": "著名的",
  "far": "远的",
  "fast": "快的",
  "fat": "胖的；脂肪",
  "February": "二月",
  "few": "少数",
  "film": "电影",
  "final": "最终的",
  "fine": "好的；精细的",
  "finish": "完成",
  "fish": "鱼",
  "five": "五",
  "floor": "地板；楼层",
  "food": "食物",
  "foot": "脚",
  "forget": "忘记",
  "four": "四",
  "Friday": "星期五",
  "fruit": "水果",
  "full": "满的；饱的",
  "game": "游戏；比赛",
  "garden": "花园",
  "girl": "女孩",
  "glass": "玻璃；杯子",
  "green": "绿色的",
  "grey": "灰色的",
  "gray": "灰色的",
  "half": "一半",
  "hand": "手",
  "happy": "高兴的",
  "hat": "帽子",
  "head": "头",
  "help": "帮助",
  "her": "她的；她",
  "him": "他",
  "home": "家",
  "homework": "家庭作业",
  "horse": "马",
  "hospital": "医院",
  "hotel": "酒店",
  "hour": "小时",
  "house": "房子",
  "hundred": "一百",
  "hungry": "饿的",
  "husband": "丈夫",
  "ice": "冰",
  "idea": "想法",
  "important": "重要的",
  "inside": "里面",
  "interesting": "有趣的",
  "internet": "互联网",
  "January": "一月",
  "juice": "果汁",
  "July": "七月",
  "June": "六月",
  "kitchen": "厨房",
  "lake": "湖",
  "late": "迟的；晚的",
  "learn": "学习",
  "leave": "离开；留下",
  "left": "左边；剩下的",
  "lesson": "课",
  "letter": "字母；信",
  "library": "图书馆",
  "life": "生活；生命",
  "little": "小的；少量",
  "lunch": "午餐",
  "make": "做；制作",
  "man": "男人",
  "many": "许多",
  "map": "地图",
  "market": "市场",
  "May": "五月",
  "meal": "一餐",
  "meat": "肉",
  "medicine": "药；医学",
  "milk": "牛奶",
  "minute": "分钟",
  "Monday": "星期一",
  "money": "钱",
  "month": "月",
  "morning": "早晨",
  "mother": "母亲",
  "mouth": "嘴",
  "movie": "电影",
  "music": "音乐",
  "name": "名字；名称",
  "near": "近的",
  "need": "需要",
  "newspaper": "报纸",
  "night": "夜晚",
  "nine": "九",
  "nineteen": "十九",
  "ninety": "九十",
  "nothing": "没有什么",
  "November": "十一月",
  "October": "十月",
  "often": "经常",
  "orange": "橙子；橙色的",
  "parent": "父母之一",
  "park": "公园",
  "party": "聚会；政党",
  "pay": "支付",
  "people": "人们",
  "phone": "电话；手机",
  "picture": "图片；照片",
  "pink": "粉色的",
  "plane": "飞机",
  "plate": "盘子",
  "please": "请；使高兴",
  "police": "警察",
  "poor": "贫穷的；差的",
  "Portuguese": "葡萄牙语；葡萄牙的",
  "post": "邮寄；帖子",
  "price": "价格",
  "problem": "问题",
  "purple": "紫色的",
  "rain": "雨；下雨",
  "red": "红色的",
  "remember": "记得",
  "rich": "富有的；丰富的",
  "right": "右边；正确的",
  "ring": "戒指；打电话",
  "river": "河",
  "road": "路",
  "room": "房间",
  "run": "跑；运行",
  "Saturday": "星期六",
  "school": "学校",
  "sea": "海",
  "search": "搜索；寻找",
  "season": "季节",
  "secret": "秘密",
  "see": "看见",
  "sell": "卖",
  "September": "九月",
  "seven": "七",
  "seventeen": "十七",
  "seventy": "七十",
  "shirt": "衬衫",
  "shop": "商店；购物",
  "sick": "生病的",
  "sister": "姐妹",
  "six": "六",
  "sixteen": "十六",
  "sixty": "六十",
  "slow": "慢的",
  "snow": "雪；下雪",
  "son": "儿子",
  "speak": "说；讲",
  "spring": "春天；弹簧",
  "start": "开始",
  "station": "车站",
  "stay": "停留；保持",
  "street": "街道",
  "student": "学生",
  "summer": "夏天",
  "Sunday": "星期日",
  "table": "桌子",
  "tea": "茶",
  "teach": "教",
  "teacher": "老师",
  "telephone": "电话",
  "ten": "十",
  "test": "测试",
  "thank": "感谢",
  "thirteen": "十三",
  "thirty": "三十",
  "thousand": "一千",
  "Thursday": "星期四",
  "ticket": "票",
  "today": "今天",
  "tomorrow": "明天",
  "train": "火车；训练",
  "tree": "树",
  "Tuesday": "星期二",
  "twelve": "十二",
  "twenty": "二十",
  "under": "在……下面",
  "understand": "理解",
  "use": "使用",
  "vegetable": "蔬菜",
  "very": "非常",
  "village": "村庄",
  "walk": "走路；散步",
  "want": "想要",
  "weather": "天气",
  "Wednesday": "星期三",
  "week": "周；星期",
  "weekend": "周末",
  "white": "白色的",
  "window": "窗户",
  "winter": "冬天",
  "woman": "女人",
  "year": "年",
  "yellow": "黄色的",
  "yesterday": "昨天",
  "you": "你；你们",
  "we": "我们",
  "they": "他们；她们；它们",
  "Portuguese": "葡萄牙语；葡萄牙的",
  "portuguese": "葡萄牙语；葡萄牙的",
  "country": "国家",
  "approximately": "大约",
  "artist": "艺术家",
  "as": "作为；像……一样；当……时",
  "athlete": "运动员",
  "backwards": "向后；倒退地",
  "bake": "烘焙；烤",
  "bar": "酒吧；条",
  "by": "由；通过；在……旁边",
  "canada": "加拿大",
  "cash": "现金",
  "catholic": "天主教的",
  "certain": "某个；确定的",
  "comedy": "喜剧",
  "conjunction": "连词",
  "count": "数数；计算",
  "danish": "丹麦语；丹麦的",
  "date": "日期；约会",
  "decorate": "装饰",
  "direct": "直接的；指挥",
  "domestic": "国内的；家庭的",
  "drama": "戏剧",
  "drive": "驾驶",
  "dry": "干的",
  "earn": "赚得",
  "each": "每个",
  "ending": "结尾；结束",
  "exhibit": "展出；展品",
  "experiment": "实验",
  "export": "出口；导出",
  "farm": "农场",
  "farmer": "农民",
  "flight": "航班；飞行",
  "forum": "论坛",
  "fresh": "新鲜的",
  "government": "政府",
  "guess": "猜测",
  "hike": "徒步旅行",
  "horrible": "可怕的",
  "incredible": "难以置信的",
  "industry": "工业；行业",
  "interview": "采访；面试",
  "invent": "发明",
  "invite": "邀请",
  "iron": "铁；熨斗",
  "jogging": "慢跑",
  "kill": "杀死",
  "kiss": "亲吻",
  "linger": "逗留；徘徊",
  "lovely": "可爱的；美好的",
  "message": "消息；信息",
  "millenium": "千年",
  "millennium": "千年",
  "misery": "痛苦；悲惨",
  "most": "最多的；大多数",
  "mountain": "山",
  "offer": "提供；提议；优惠",
  "order": "命令；订单；顺序",
  "past": "过去；经过",
  "pepper": "胡椒；辣椒",
  "perfect": "完美的",
  "pillow": "枕头",
  "plan": "计划",
  "popular": "受欢迎的",
  "quick": "快的；迅速的",
  "rail": "铁轨；栏杆",
  "really": "真的；非常",
  "reception": "接待；招待会",
  "relationship": "关系",
  "relax": "放松",
  "repeat": "重复",
  "sale": "出售；促销",
  "salesperson": "销售员",
  "sad": "难过的",
  "sandwich": "三明治",
  "seek": "寻找；寻求",
  "seem": "似乎",
  "several": "几个；若干",
  "shampoo": "洗发水",
  "should": "应该",
  "sign": "签名；标志",
  "simple": "简单的",
  "smoke": "烟；吸烟",
  "soon": "很快",
  "spend": "花费；度过",
  "square": "广场；正方形",
  "steak": "牛排",
  "stepfather": "继父",
  "subject": "主题；主语；科目",
  "success": "成功",
  "suggest": "建议",
  "survey": "调查",
  "swim": "游泳",
  "take": "拿；带；花费",
  "thai": "泰语；泰国的",
  "thin": "瘦的；薄的",
  "thing": "东西；事情",
  "think": "认为；思考",
  "through": "穿过；通过",
  "tie": "领带；系",
  "tip": "提示；小费",
  "unfortunately": "不幸地；遗憾地",
  "underlined": "加下划线的",
  "usually": "通常",
  "why": "为什么",
  "will": "将要；意愿",
  "wolf": "狼",
  "wonderful": "精彩的；美妙的",
});

Object.assign(phraseTranslations, {
  "biodiversity": "生物多样性",
  "baltic sea": "波罗的海",
  "book a room;place to live": "预订房间或住处",
  "book a room；place to live": "预订房间或住处",
  "ciao! see you!": "再见；回头见",
  "completely sick;crazy": "完全病态；非常疯狂",
  "completely sick；crazy": "完全病态；非常疯狂",
  "could you say that again": "你能再说一遍吗",
  "do you follow": "你明白了吗",
  "don't make a big deal out of it": "别把这件事看得太严重",
  "don&#x27;t make a big deal out of it": "别把这件事看得太严重",
  "excuse me/i'm sorry do you have a moment": "不好意思，你有时间吗",
  "excuse me/i'm sorry, do you have a moment": "不好意思，你有时间吗",
  "excuse me/ i'm sorry do you have a moment": "不好意思，你有时间吗",
  "excuse me/ i'm sorry, do you have a moment": "不好意思，你有时间吗",
  "compulsive liar": "惯于说谎的人",
  "easter holiday": "复活节假期",
  "female teacher": "女教师",
  "(female) teacher": "女教师",
  "hi it's been a long time": "嗨，好久不见",
  "hi! it's been a long time!": "嗨，好久不见",
  "hi! it's been a long time": "嗨，好久不见",
  "hi! it’s been a long time!": "嗨，好久不见",
  "hi! it’s been a long time": "嗨，好久不见",
  "hope you are all well": "希望你们一切都好",
  "hope you are all well!": "希望你们一切都好",
  "i don't understand": "我不明白",
  "i found… on the internet": "我在网上找到了",
  "i'm fine": "我很好",
  "in the end…": "最后；最终",
  "instead of…": "代替；而不是",
  "wish list": "愿望清单",
  "wonder why": "想知道为什么",
  "solid;genuine": "可靠的；真诚的",
  "solid；genuine": "可靠的；真诚的",
  "%": "百分号；百分比",
});

Object.assign(wordTranslations, {
  "certainly": "当然；确实",
  "compose": "创作；组成",
  "composer": "作曲家",
  "complaint": "投诉；抱怨",
  "complex": "复杂的",
  "compound": "复合的；复合词",
  "comprehensible": "可理解的；清楚的",
  "compromise": "妥协",
  "concentrate": "集中注意力",
  "conclusion": "结论",
  "concrete": "具体的；混凝土",
  "condemn": "谴责",
  "condescending": "居高临下的；傲慢的",
  "condensed": "浓缩的；压缩的",
  "confirm": "确认",
  "connection": "联系；连接",
  "conserve": "保存；保护",
  "denmark": "丹麦",
  "firstly": "首先",
  "greenlandic": "格陵兰语；格陵兰的",
  "hardworking": "勤奋的",
  "harmonious": "和谐的",
  "id": "身份证件；证件",
  "intelligent": "聪明的",
  "interrupt": "打断；中断",
  "negative": "否定的；消极的",
  "punishment": "惩罚",
  "sold": "已售出；被卖掉",
  "up": "帮忙；支持",
});

main();
